### ISSUE TITLE
Compatability with Cardbook extension

### ISSUE THREAD

**Issue by trevor87** [ingomueller-net/ThunderBirthDay#10]
Hi!

I just installed this extension and was wondering why it does not show any birthdays.. Then I realized, that it does not work for me as I use the cardbook extension (which allows proper synchronisation of the adressbook with CardDaV). Is it possible to use it with the adressbook of that extension somehow?

Thanks!

**Comment by klemens** [comment]
Doesn't CardBook come with its own birthday implementation?
If you want to sync your contacts with the normal address-book, you can use [TbSync](https://addons.thunderbird.net/thunderbird/addon/tbsync/), which works fine in combination with ThunderBirthDay. :wink:

**Comment by trevor87** [comment]
Hi klemens!

Thanks for your hint! You are right, cardbook has this feature too. I just had to activate it..

Sorry for bothering you guys!
