### ISSUE TITLE
Not compatible with Thunderbird 68.1.1

### ISSUE THREAD

**Issue by MaDill** [ingomueller-net/ThunderBirthDay#13]
I received the update to Thunderbird 68.1.1 and I found that most of the extensions are not working anymore. Some I kicked, but ThunderBirthDay I want to keep. I hope you can fix this.

In this bug [https://bugzilla.mozilla.org/show_bug.cgi?id=151994](url) is also less activity and it is filed 18 years ago. When there is no native integration of this usefull addon, then please make it working again. Thanks.

**Comment by klemens** [comment]
See #11, there is also a preview of the fixed version available.

**Comment by MaDill** [comment]
Thank you @klemens. Hopefully @ingomueller-net will release your version soon.
