### ISSUE TITLE
Broken compatibility with Thunderbird 60.0

### ISSUE THREAD

**Issue by BierGitte** [ingomueller-net/ThunderBirthDay#8]
Mozilla broke most addons with the recent update, ThunderBirthDay is one of them.
Mozilla's update note:

> IMPORTANT: Add-ons not marked as compatible with Thunderbird 60 by their authors will be disabled (this can be reverted via preference extensions.strictCompatibility)

However, forcing Thunderbird to accept old addons doesn't work.
Error message on restart:

> Beim Bereitstellen des Kalenders mit der Adresse moz-abdirectory:// ist ein Fehler aufgetreten. Er wird nicht verfügbar sein.

**Comment by ingomueller-net** [comment]
I just marked the add-on as compatible on [addons.thunderbird.net](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderbirthday/), which wasn't the case previously. Does that solve the problem?

**Comment by BierGitte** [comment]
Thanks for the fast fix! I just tested it and it works fine.

I still wonder why it didn't when I forced TB to accept it with extensions.strictCompatibility disabled.

**Comment by ingomueller-net** [comment]
OK, great, thanks for reporting the problem and the outcome of the fix.

**Comment by ingomueller-net** [comment]
Other users have reported this problem even after the update. I am now tracking it in #9.
