### ISSUE TITLE
Creating calendar fails with error

### ISSUE THREAD

**Issue by ingomueller-net** [ingomueller-net/ThunderBirthDay#9]
Users are reporting to me that creation of calendars is broken. They get the following error at the end of the calendar creation dialogue:

> [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getIntPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: jar:file:///C:/Users/User/AppData/Roaming/Thunderbird/Profiles/fcqbcs51.stw/extensions/%7B4C9FE6FE-2C83-11DC-90B4-DC8456D89593%7D.xpi!/js/calThunderBirthDay.js :: MyLOG :: line 948"  data: no]

The [related line](https://github.com/ingomueller-net/ThunderBirthDay/blob/master/src/js/calThunderBirthDay.js#L948) looks like this:

    MyLOG.mVerbosity = Components.classes["@mozilla.org/preferences-service;1"]
                                 .getService(Components.interfaces.nsIPrefService)
                                 .getBranch("extensions.thunderbirthday.")
                                 .getIntPref("verbosity");

At a first glance, it seems like `getIntPref` has changed and now throws an exception if the value does not exist. It probably needs a default parameter `aDefaultValue`, see [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIPrefBranch#getIntPref()).

I do not have time to try it. Help would be greatly appreciated.

**Comment by ingomueller-net** [comment]
I have created a test version with `.getIntPref("verbosity", 0);`, but two users told me that that doesn't fix the problem. Can anyone confirm?

**Comment by ingomueller-net** [comment]
Also, it seems like the problem also occurs on already-existing calendars.

**Comment by ingomueller-net** [comment]
Could somebody who experiences the problem let me know what the configuration value of `extensions.thunderbirthday.verbosity` is? To do that, do the following:

1. Open the config editor as described [here](https://support.mozilla.org/en-US/kb/config-editor).
1. Type `extensions.thunderbirthday.verbosity`.
1. Report below what value and what type the entry has (if present).
1. Try to add it/change it to 0 of type integer and see whether the problem goes away.

**Comment by mbrohl** [comment]
This seems to work for me (I had to remove the existing calendar and create a new one).

**Comment by ingomueller-net** [comment]
@mbrohl You set it to 0? What was the value before? Not present I assume?

**Comment by mbrohl** [comment]
Yes, it was not present and I set it to 0.

**Comment by ingomueller-net** [comment]
Great, thanks for the confirmation! Meanwhile, another user has confirmed that this method works.

What I don't understand is why `.getIntPref("verbosity", 0);` does not work. Also, why isn't the [value from `user.js`](https://github.com/ingomueller-net/ThunderBirthDay/blob/master/src/defaults/preferences/user.js#L39) inserted at installation?

**Comment by ulln** [comment]
Remove this line:
https://github.com/ingomueller-net/ThunderBirthDay/blob/5a9769750174e1ece6ca882a96290150f6bcf664/src/defaults/preferences/user.js#L1

https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Default_Preferences
> The actual file, despite having .js extension, is not a JavaScript file. You may not set variables inside of it, nor may do any kind of program flow control (ifs, loops etc.) nor even calculated values (i.e. 3600 * 24 * 5). Doing so will cause Mozilla to stop processing your preferences file without any notification, warning, error, or exception. Think of it more as an .ini file. Comments are perfectly acceptable.

**Comment by inklebott** [comment]
I've had the same problem today after Thunderbirthday updated yesterday (Tbird 52.5.0 on Linux Mint 18 Cinnamon) 
Adding "extensions.thunderbirthday.verbosity 0" as above has fully restored functionality.
Thank you.

**Comment by ingomueller-net** [comment]
Thanks @ulln for the pointer! That did the trick :) Thanks everybody else for testing.

I created a new version. Once it has been reviewed, it should be available [here](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderbirthday/versions/0.8.3).

**Comment by klemens** [comment]
Oops, sorry about that. `preferences/install.js` still contains `"use strict";`, although it currently works fine here (the description string is displayed correctly, maybe because it is not retrieved programmatically?).
